V  = [ ] 
n1 = int(input("Primeiro número:"))
n2 = int(input("Segundo número:"))
n3 =int(input("Terceiro número:"))
n4 = int(input("Quarto número:"))
n5 = int(input("Quinto número:"))
V.append(n1) 
V.append (n2) 
V.append (n3) 
V.append (n4) 
V.append (n5) 
print(n1) 
print(n2)
print(n3)
print(n4)
print(n5)